# -*- coding: utf-8 -*-
"""dMNIST_client1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dyLXfG4Liln-yY8rdkD6DqjVvyRiYLtU
"""

#Code taken and modified from https://keras.io/examples/vision/mnist_convnet/ from user https://twitter.com/fchollet creator of Keras

import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from time import perf_counter

TRAIN_SIZE = 12500

# Model / data parameters
num_classes = 10
input_shape = (28, 28, 1)

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Scale images to the [0, 1] range
x_train = x_train.astype("float32") / 255
x_test = x_test.astype("float32") / 255
# Make sure images have shape (28, 28, 1)
x_train = np.expand_dims(x_train, -1)
x_test = np.expand_dims(x_test, -1)

x_tune = x_train[50000:]
x_train = x_train[0:TRAIN_SIZE]


print("x_train shape:", x_train.shape)
print(x_train.shape[0], "train samples")
print(x_test.shape[0], "test samples")

y_tune = y_train[50000:]
y_train = y_train[0:TRAIN_SIZE]


# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
y_tune = keras.utils.to_categorical(y_tune, num_classes)

model = keras.Sequential(
    [
        keras.Input(shape=input_shape),
        layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Flatten(),
        layers.Dropout(0.5),
        layers.Dense(num_classes, activation="softmax"),
    ]
)

model.summary()


model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["categorical_accuracy"])

import socket
import pickle

HEADERSIZE = 10

TOTAL_EPOCHs = 3

def run_epoch_get_wnl():
  batch_size = 128
  epochs = 1
  model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs)
  score = model.evaluate(x_tune,y_tune)
  return [np.array(model.get_weights()),score[0]]

for x in range(TOTAL_EPOCHs):
  # Start the stopwatch / counter 
  t1_start = perf_counter() 
  run_epoch_get_wnl()
  # Stop the stopwatch / counter 
  t1_stop = perf_counter()
  f = open("epoch12k.csv", "a")
  f.write(str(t1_stop-t1_start))
  f.write("\n")
  f.close()

#msg = bytes(f"{len(msg):<{HEADERSIZE}}", 'utf-8')+pickle.dumps("DONE")
#s.send(msg)
